aws_access_key_id: null
aws_region: us-west-2
aws_secret_access_key: null
perplexity_api_key: null
batch_size: 2
chat_dataset: true
chat_template: Llama3.1
count_synthetic_data: 1000
data_config_file: ''
data_location: C:\Users\marclobr\Documents\Partner Demos\Misc Dev\llama-automate\usecase_data\fsi-loan
endpoint_name: ''
epochs: 1
generate_synthetic_data: true
huggingface_model_flag: true
huggingface_token: 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
input_data_s3_bucket: amazon-sagemaker-605134472325-us-west-2-798b8de84f6d
input_data_s3_file_path: ''
input_data_s3_prefix: usecase_data
instance_type: ml.g5.12xlarge
jumpstart_model_id: meta-textgeneration-llama-3-2-1b
learning_rate: 2e-5
local_input_data_path: usecase_data/patient_care_plan/patient_care_plan_dialog_0619_1415.jsonl
local_model_flag: false
local_model_path: null
lora_alpha: 64
lora_r: 16
max_input_length: 2048
model_files_s3_bucket: ''
model_name: ''
model_tar_s3_file_path: ''
model_type: chat
output_model_files_s3_bucket: ''
s3_jsonl_file: usecase_data/patient-care-plan/patient-care-plan.jsonl
sagemaker_role: arn:aws:iam::605134472325:role/service-role/AmazonSageMaker-ExecutionRole-20250203T150785
uri_for_uploaded_s3_input_data: ''
use_case: fsi-loan
using_existing_data: true
validation_split: 0.25
